services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scalefusion-webhook
    ports:
      - "${FLASK_PORT:-5000}:5000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
